### ISSUE TITLE
Cannot install Node on M1 Max

### ISSUE THREAD

**Issue by abdirahmanjama** [aredridel/node-bin-gen#175] opened 2022-09-14 22:53 UTC
Hi @aredridel, 

I'm unable to install node as a dependency on my M1 Max - I believe I'm experiencing this issue because the version of node required by my application isn't listed on: https://www.npmjs.com/package/node-darwin-arm64. Any chance we can update the versions listed on here to match: https://nodejs.org/download/release/v16.13.2/ 

Thanks 🙏

<img width="1032" alt="Screenshot 2022-09-14 at 12 15 32" src="https://user-images.githubusercontent.com/45077645/190276182-2743fff8-ee62-4f57-b9e7-1f8964ef1dae.png">

**Comment by styfle** [comment] 2022-10-03 23:53
This looks like a duplicate of #143

**Comment by aredridel** [comment] 2022-10-04 03:47
Try now. I just made an update to node-bin-setup that should fix this.

**Comment by styfle** [comment] 2022-10-04 23:26
Works great, thanks! 🎉

**Closed** 2022-10-13 16:56 UTC
